/**
 * `atlas agent [--workspace <ws>]`
 *
 * Generates the agent-facing artifacts for a workspace and prints how to wire
 * them in. Everything generated lands in the data store (~/.atlas/<ws>/), never
 * in target repos (ADR 0003) — the user adds only a one-line import to their
 * repo's CLAUDE.md.
 *
 *   architecture.md      greppable summary an agent can just read
 *   atlas.steering.md    always-on steering: what Atlas is + when/how to use it
 *
 * This is the surviving "patterns file" idea from the roadmap: the always-on
 * context that makes a coding agent reach for Atlas without being told.
 */

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as fs from "node:fs";
import { linkRepos } from "../core/link.js";
import { systemDiagram } from "../core/mermaid.js";
import { Graph } from "../core/graph.js";
import { topHubs, suggestedQuestions } from "../core/orientation.js";
import type { ExtractorOutput, Manifest, MergedMap } from "../core/schema.js";
import {
  readAllTopologies,
  readDetection,
  readManifest,
  readMap,
  workspaceDir,
} from "./store.js";
import { resolveWorkspace } from "./workspace.js";

// tool root = two levels up from dist/cli/agent.js
const TOOL_ROOT = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const ATLAS_BIN = join(TOOL_ROOT, "bin", "atlas.js");

export function runAgent(args: string[]): number {
  const ws = resolveWorkspace(parseWorkspace(args));
  if (!ws) return 1;

  const { archPath, steerPath } = writeAgentFiles(ws);
  console.error(`wrote ${archPath}`);
  console.error(`wrote ${steerPath}`);
  console.error(wiringInstructions(ws, steerPath));
  return 0;
}

/**
 * (Re)generate the agent-facing files for a workspace into the data store.
 * Shared by `atlas agent` and `atlas refresh`. Returns the written paths.
 */
export function writeAgentFiles(ws: string): { archPath: string; steerPath: string } {
  const manifest = readManifest(ws);
  const topologies = readAllTopologies(ws);
  let map: MergedMap;
  try {
    map = readMap(ws);
  } catch {
    map = linkRepos(topologies, { workspace: ws, generatedAt: new Date().toISOString() });
  }

  const dir = workspaceDir(ws);
  const archPath = join(dir, "architecture.md");
  const steerPath = join(dir, "atlas.steering.md");
  fs.writeFileSync(archPath, architectureMd(manifest, topologies, map), "utf8");
  fs.writeFileSync(steerPath, steeringMd(ws, manifest), "utf8");
  return { archPath, steerPath };
}

function architectureMd(m: Manifest, tops: ExtractorOutput[], map: MergedMap): string {
  const L: string[] = [];
  L.push(`# Architecture — workspace "${m.workspace}"`);
  L.push("");
  L.push(`Generated by atlas. A *hint* to verify against real code, not authority.`);
  L.push("");

  // Orientation digest — most-depended-on code + scoped questions to ask.
  const wg = new Graph(
    tops.flatMap((t) => t.nodes),
    [
      ...tops.flatMap((t) => t.edges),
      ...map.crossRepoEdges.map((e) => ({ from: e.from, to: e.to, kind: "http" as const, line: 0 })),
    ],
  );
  const hubs = topHubs(wg, 8);
  if (hubs.length > 0) {
    L.push(`## Orientation (read first)`);
    L.push(`Most-depended-on functions (by caller count — change these carefully):`);
    for (const h of hubs) L.push(`- \`${h.node.name}\` — ${h.callers} callers (${h.node.file})`);
    L.push("");
    L.push(`Ask the map (CLI \`atlas …\` or the \`atlas_*\` MCP tools) instead of reading files:`);
    for (const q of suggestedQuestions(hubs, map)) L.push(`- ${q}`);
    L.push("");
  }

  L.push(`## Repos (${m.repos.length})`);
  for (const r of m.repos) {
    L.push(`- **${r.id}** (${r.role}, ${r.language}) — \`${r.path}\``);
    const d = readDetection(m.workspace, r.id);
    if (d) {
      L.push(`  - languages: ${d.languages.join(", ") || "?"}`);
      if (d.frameworks.length) L.push(`  - frameworks: ${d.frameworks.join(", ")}`);
    }
  }
  L.push("");
  L.push(`## Per-repo summary`);
  for (const t of tops) {
    const fns = t.nodes.filter((n) => n.kind === "function").length;
    const calls = t.edges.filter((e) => e.kind === "call").length;
    L.push(
      `- **${t.repo}**: ${fns} functions, ${calls} calls, ` +
        `${t.endpoints.consumes.length} consumes, ${t.endpoints.exposes.length} exposes`,
    );
  }
  L.push("");
  L.push(`## Cross-repo links (${map.crossRepoEdges.length})`);
  for (const e of map.crossRepoEdges) L.push(`- \`${e.contract}\`: ${e.from} → ${e.to}`);
  if (map.crossRepoEdges.length === 0) L.push(`- _(none resolved yet)_`);
  L.push("");
  L.push(`## External endpoints — consumed, not exposed here (${map.externalNodes.length})`);
  L.push(`The backends this workspace depends on but does not contain:`);
  for (const n of map.externalNodes) {
    L.push(`- \`${n.id.replace(/^external:/, "")}\` — ${n.consumedBy.length} call site(s)`);
  }
  L.push("");
  L.push(`## System diagram`);
  L.push("```mermaid");
  L.push(systemDiagram(map));
  L.push("```");
  L.push("");
  L.push(`## Machine-readable detail`);
  L.push(`- \`map.json\` — merged cross-repo map`);
  L.push(`- \`<repo>.topology.json\` — per-repo nodes/edges/endpoints`);
  L.push("");
  return L.join("\n");
}

function steeringMd(ws: string, m: Manifest): string {
  const repos = m.repos.map((r) => `${r.id} (${r.role})`).join(", ");
  const stack = m.repos
    .map((r) => {
      const d = readDetection(ws, r.id);
      if (!d) return null;
      const fw = d.frameworks.length ? ` — ${d.frameworks.join(", ")}` : "";
      return `${r.id}: ${d.languages.join(", ")}${fw}`;
    })
    .filter(Boolean);

  return `# Atlas — structured cross-repo map (always-on context)

This repo is connected to **Atlas workspace \`${ws}\`** (repos: ${repos}).
Atlas is a local tool that holds the *structured, cross-repo map* of this system:
who calls whom, which frontend calls map to which backend endpoints, and what
breaks if you change something.
${stack.length ? `\nDetected stack (auto): ${stack.join("; ")}.\n` : ""}

## Division of labor — important
- **You** do in-repo discovery (grep/glob/read). You are better at that than any index.
- **Atlas** provides the cross-repo structure and call graph you can't cheaply derive
  by searching. Don't grep across repos to reconstruct it — ask Atlas.
- The map is a **hint to verify against real code**, never authority. It can be stale;
  re-run \`atlas scan\` if it looks wrong.

## When to use Atlas (without being asked)
- **Before editing/renaming/deleting a function** → \`atlas impact <symbol> -w ${ws}\`
  (transitive callers + cross-repo consumers — the blast radius).
- **Orienting in unfamiliar code** → \`atlas context <symbol|file> -w ${ws}\`
  (the thing + its callers + callees).
- **"What backend does this call?" / cross-repo questions** → \`atlas endpoints -w ${ws}\`.

## How to call it
- CLI: \`atlas <context|impact|endpoints> ... -w ${ws}\` (omit \`-w\` if only one workspace).
- MCP tools (if the atlas MCP server is configured): \`atlas_context\`, \`atlas_callers\`,
  \`atlas_impact\`, \`atlas_endpoints\`. Prefer these for structured results.

## Read for a quick overview
- \`~/.atlas/${ws}/architecture.md\` — summary (repos, links, external backends).
`;
}

function wiringInstructions(ws: string, steerPath: string): string {
  return `
To make a coding agent auto-aware of Atlas:

  • Claude Code — add this line to the target repo's CLAUDE.md (imports the steering file):
        @${steerPath}

  • Register the MCP server (structured tools) for Claude Code:
        claude mcp add atlas -- node ${ATLAS_BIN} mcp
    …or add to .mcp.json:
        { "mcpServers": { "atlas": { "command": "node", "args": ["${ATLAS_BIN}", "mcp"] } } }

  • Cursor: paste ${steerPath} into .cursor/rules. Kiro: add it as a steering file.

Re-run \`atlas agent -w ${ws}\` after re-scanning to refresh architecture.md.`;
}

function parseWorkspace(args: string[]): string | undefined {
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--workspace" || args[i] === "-w") return args[i + 1];
  }
  return undefined;
}
